#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum RelocKind {
    None,
    R32,
    R64,
    Relative,
    Copy,
    JumpSlot,
    TlsDtpMod32,
    TlsDtpMod64,
    TlsDtprel32,
    TlsDtprel64,
    TlsTprel32,
    TlsTprel64,
    Branch,
    Jal,
    Call,
    CallPlt,
    GotHi20,
    TlsGotHi20,
    TlsGdHi20,
    PcrelHi20,
    PcrelLo12I,
    PcrelLo12S,
    Hi20,
    Lo12I,
    Lo12S,
    TprelHi20,
    TprelLo12I,
    TprelLo12S,
    TprelAdd,
    Add8,
    Add16,
    Add32,
    Add64,
    Sub8,
    Sub16,
    Sub32,
    Sub64,
    GnuVtInherit,
    GnuVtEntry,
    Align,
    RvcBranch,
    RvcJump,
    RvcLui,
    Relax,
    Sub6,
    Set6,
    Set8,
    Set16,
    Set32,
    Pcrel32,
    Irelative,
    Reserved(u32),
    Unknown(u32),
}

impl RelocKind {
    pub const fn from_u32(kind: u32) -> RelocKind {
        use RelocKind::*;

        match kind {
            0 => None,
            1 => R32,
            2 => R64,
            3 => Relative,
            4 => Copy,
            5 => JumpSlot,
            6 => TlsDtpMod32,
            7 => TlsDtpMod64,
            8 => TlsDtprel32,
            9 => TlsDtprel64,
            10 => TlsTprel32,
            11 => TlsTprel64,
            16 => Branch,
            17 => Jal,
            18 => Call,
            19 => CallPlt,
            20 => GotHi20,
            21 => TlsGotHi20,
            22 => TlsGdHi20,
            23 => PcrelHi20,
            24 => PcrelLo12I,
            25 => PcrelLo12S,
            26 => Hi20,
            27 => Lo12I,
            28 => Lo12S,
            29 => TprelHi20,
            30 => TprelLo12I,
            31 => TprelLo12S,
            32 => TprelAdd,
            33 => Add8,
            34 => Add16,
            35 => Add32,
            36 => Add64,
            37 => Sub8,
            38 => Sub16,
            39 => Sub32,
            40 => Sub64,
            41 => GnuVtInherit,
            42 => GnuVtEntry,
            43 => Align,
            44 => RvcBranch,
            45 => RvcJump,
            46 => RvcLui,
            51 => Relax,
            52 => Sub6,
            53 => Set6,
            54 => Set8,
            55 => Set16,
            56 => Set32,
            57 => Pcrel32,
            58 => Irelative,
            _ => Unknown(kind),
        }
    }
}
